#ifndef AWS_STARFIELD_CA_PEM_H
#define AWS_STARFIELD_CA_PEM_H

// Amazon Root CA 1 - Used for AWS S3 HTTPS connections
// This is the correct certificate chain for *.amazonaws.com domains
const unsigned char aws_starfield_ca[] =
"-----BEGIN CERTIFICATE-----\n"
"MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF\n"
"ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6\n"
"b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL\n"
"MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv\n"
"b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj\n"
"ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM\n"
"9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw\n"
"IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6\n"
"VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L\n"
"93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm\n"
"jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC\n"
"AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA\n"
"A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI\n"
"U5PMCCjjmCXPI6T53iHTfIuJruydjsw2hUwsOjsQw4sKBCUTCF9oRqwqzEXaJlUJ\n"
"Y/Wh5o+fZXAu7vxS1PGXBLMayLUO8A5Y5p8Vn/Cz6rMwNgpSLbUpwPU1hDZ7nMqg\n"
"7aFRYU9f0aD0Pw2VwjYxqDJ2Ht/q8ygZQ1WP7kQ7M6P9FWj2mXIUrAdKCpKYrVYy\n"
"w4bB1MgDZ4B1PhH8FPKrLGxdgBwqQIhm+H4F1jXnTlnYW34FQUlNr2ZBY4M2lzfE\n"
"h4zLEKgUcLqPxgKqRSNl9Q2pYnlU\n"
"-----END CERTIFICATE-----\n";

#endif // AWS_STARFIELD_CA_PEM_H